# Generated by Django 5.2 on 2025-04-10 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snippets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('tags', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('supabase_user_id', models.CharField(db_index=True, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='bookmarks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets_service.snippets')),
            ],
        ),
    ]
